#!/bin/bash

BH_IP=(bh_cmd_wget -q https://www.mentebinaria.com.br/ext/ip.php -O -)
[[ "${BH_IP}" =~ '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' ]] || BH_IP=$(bh_cmd_wget -q https://api.ipify.org -O -)
[[ "${BH_IP}" =~ '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' ]] && echo "${BH_IP}"
