#!/bin/bash

[[ $# -ne 1 ]] && exit 1 

. /usr/local/etc/bashack.conf

[[ -d "${BASHACKS_CACHEDIR}" ]] || mkdir -p "${BASHACKS_CACHEDIR}"

BH_CACHEFILE="${BASHACKS_CACHEDIR}/${1}.txt"

if [[ -s "${BH_CACHEFILE}" ]]; then
  cat "${BH_CACHEFILE}"
else
  bh_cmd_wget -q http://faydoc.tripod.com/cpu/${1}.htm -O - | \
    html2text | \
    sed -n '/^===.*/,$p' | \
    sed 's/^===.*/'${1}'/' | \
    tr _ ' ' | \
    tee -a "${BH_CACHEFILE}"
fi

[[ -s "${BH_CACHEFILE}" ]] || rm -f "${BH_CACHEFILE}"
