#!/bin/bash

if [ $# -ne 3 ]
then
  echo 'Usage: bh_charcalc <ch> <op> <ch>'
  exit 1
fi

case "$2" in
  +|-)  for i in $(echo "${1}" | sed 's/./& /g'); 
        do
          char=$(bh_asc2dec ${i})
          res=$((${char} ${2} ${3}))
          echo -n $(bh_dec2asc ${res})
        done
        echo
        ;;
  '*')  for (( i=0; i<$3; i++ ))
        do
          res="${res}${1}"
        done
        echo ${res}
        ;;
esac

